### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [chesare40/prj-rev-bwfs-tea-cozy#3]
Overall excellent project.

Your html and css were well organized.  Your css was very efficient, I didn't see any major repetition at all.  It showed you have an understanding of how to manage multiple selectors together.

So to prepare you for the upcoming projects as a challenge I like you to use media queries and make this site look like an app on a mobile device. Media queries will be a major part of the rest of your remaining curriculum.

**Comment by chesare40** [comment]
Hi!
Thank you very much for the feedback! I will make sure to continue improving and definitely add a media queries.

Thanks again!
